### ISSUE TITLE
Question: How to do manange header and footer

### ISSUE THREAD

**Issue by garrypolley** [Crownpeak/DXM-React-SDK#15]
What is the recommended way to manage a header and footer in using this SDK? 

Would an `index.html` like the following work? 

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Editor View For Pages</title>
        <link href="/path/to/output.css" rel="stylesheet">
    </head>

    <body>
        {MainNavigation:Widget}
        <div id="app" data-cms-wrapper-name="WrapperName"></div>
        {MainFooter:Widget}
    </body>

</html>
```

The goal is that the `MainNavigation` and `MainFooter` are managed ocne in the CMS and are the same on all pages using the wrapper.  

When the data is written from the `output_json.aspx` for a template ideally the output JSON includes those elements as well. 

```json
{
    "MainNavigation": JSON,
     "DropZones": [],
     "MainFooter": JSON
}
```

Then the app can more easily render what's needed.

**Comment by ptylr** [comment]
I've just made a commit to the SDK Examples repo to cover exactly this functionality. See below:

https://github.com/Crownpeak/DXM-SDK-Examples/commit/708c74e458e7c7349e3443e39e50241c26129d7c#diff-5003ce3126c08cd408abeb20a9db41178090fd5d769343068701e5d6d7432b33

We've added a new component to handle the administration of the Header (in our case, Navigation Items), and called this HeaderNavigationAdmin - it is loaded into a new CmsPage called "Admin", which is manually created inside an "Admin" folder in the CMS so that permissions can be changed to lock down those with access. We have then created a further component, called HeaderNavigation, to handle the rendering in both CMS preview, as well as output on each page. In this component, we've allowed it to source its data from either CmsDynamicDataProvider or CmsStaticDataProvider, and you'll see the corresponding JSON in the /content/json folder (283076.json). The only thing that was not built using SDK Scaffolding was the manual creation (and code editing) of HeaderNavigationPreview, whose code is below:

```
public override string ComponentOutput(Asset asset, OutputContext context, string name, string index = "", bool isDrag = false)
{
	return Asset.Load(284076).Show();
}
```

Net result, is a new page in the CMS, for admin of the Navigation (or anything else), that publishes its own JSON to the Dynamic Content API or filesystem, that is then consumed by every other page that needs it.

This does not save you from including the header navigation on each page, just that you don't have to manage the data on each page (i.e., change to navigation results in publish of _every_ page).
